#!/bin/bash

codes=(
Df0LxQPeAtcF1wXeAt4CQAWAAwvXBd4C3gLXBdcF74bgOiMCBdcF
DdcL4APbAtYF1gXbAtsCQAWAAwvWBdsC2wLWBdYFKIfgOiMCBdYF
DdgL1APcAtcF1wXcAtwCQAWAAwvXBdwC3ALXBdcFE4fgOiMCBdcF
DfEL1APgAtQF1AXgAuACQAWAAwvUBeAC4ALUBdQFAYfgOiMCBdQF
Dc8L7QPYAtcF1wXYAtgCQAWAAwvXBdgC2ALXBdcFHofgOiMCBdcF
DekLxgPaAtkF2QXaAtoCQAWAAwvZBdoC2gLZBdkFI4fgOiMCBdkF
DfsL2QPcAtYF1gXcAtwCQAWAAwvWBdwC3ALWBdYFIIfgOiMCBdYF
DeYLzwPaAtkF2QXaAtoCQAWAAwvZBdoC2gLZBdkFOIfgOiMCBdkF
DdsL3gPdAtUF1QXdAt0CQAWAAwvVBd0C3QLVBdUFOofgOiMCBdUF
Dd8L5APdAtQF1AXdAt0CQAWAAwvUBd0C3QLUBdQF8YbgOiMCBdQF
DdIL6gPbAtQF1AXbAtsCQAWAAwvUBdsC2wLUBdQFN4fgOiMCBdQF
DfoL2QPcAtcF1wXcAtwCQAWAAwvXBdwC3ALXBdcF8YbgOiMCBdcF
De8LxAPcAtgF2AXcAtwCQAWAAwvYBdwC3ALYBdgFHYfgOiMCBdgF

"    DeEL2APWAtcF1wXWAtYCQAWAAwHXBcAJAe6G4DojAgLXBQ=="
"    DdYL3QPVAtkF2QXVAtUCQAWAAwHZBcAJARmH4F4jAgLZBQ=="
"    Dd0L6APYAtYF1gXYAtgCQAWAAwHWBcAJARqH4DojAgLWBQ=="
"    DeUL5wPWAtcF1wXWAtYCQAWAAwHXBcAJARqH4DojAgLXBQ=="
"    DeIL5gPXAtgF2AXXAtcCQAWAAwHYBcAJAeqG4DojAgLYBQ=="
"    DekLzQPaAtMF0wXaAtoCQAWAAwHTBcAJASWH4DojAgLTBQ=="
"    DcML5wPUAtkF2QXUAtQCQAWAAwHZBcAJASuH4DojAgLZBQ=="
"    DeYL2QPZAtcF1wXZAtkCQAWAAwHXBcAJARiH4DojAgLXBQ=="
"    Db8L4wPXAtgF2AXXAtcCQAWAAwHYBcAJAS6H4DojAgLYBQ=="
"    DeIL5gPVAtgF2AXVAtUCQAWAAwHYBcAJARaH4DojAgLYBQ=="
"    De0L4APWAtgF2AXWAtYCQAWAAwHYBcAJAeuG4DojAgLYBQ=="
)

for code in "${codes[@]}"; do
    echo -n "${code} -> "
    echo "${code}" | base64 -d | hexdump -v -e '/1 "%02x "' ; echo
done
